// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPYBSkbobxxc_cdIx_7keNzqW1gLJapM',
    appId: '1:332824633051:web:8d5bf82574ce91f85bb6fe',
    messagingSenderId: '332824633051',
    projectId: 'nthusiast-fbeb3',
    authDomain: 'nthusiast-fbeb3.firebaseapp.com',
    storageBucket: 'nthusiast-fbeb3.appspot.com',
    measurementId: 'G-K1LBG8N4D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ00w4q2XH9E0bfGm4Q0Yq9H2zIyh8C5M',
    appId: '1:332824633051:android:fb2d19226a58ea1a5bb6fe',
    messagingSenderId: '332824633051',
    projectId: 'nthusiast-fbeb3',
    storageBucket: 'nthusiast-fbeb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuzWPtiFjPVPJkdv5nkzDCJ0cFAV3fcgw',
    appId: '1:332824633051:ios:63a3f3daeba30c895bb6fe',
    messagingSenderId: '332824633051',
    projectId: 'nthusiast-fbeb3',
    storageBucket: 'nthusiast-fbeb3.appspot.com',
    iosClientId: '332824633051-1511frcs5lio1u2cl29dsc4qevintabu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nthusiast',
  );
}
